version: '3'

volumes:
  ecommerce-database:
    external: true

networks:
  laravel-ecommerce-network:
    external: true

services:
  ecommerce-database:
    image: mysql:5.7
    volumes:
      - ecommerce-database:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    networks:
      - laravel-ecommerce-network

  laravel-ecommerce:
    image: ambientum/php:7.3-nginx
    container_name: laravel-ecommerce
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - laravel-ecommerce-network
